version: '3.3'
services: 
    dataserver: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver:12345
      ports: 
        - 12345:12345
    dataserver2: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver2:12345
      ports: 
        - 12346:12345
    dataserver3: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver3:12345
      ports: 
        - 12347:12345
    dataserver4: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver4:12345
      ports: 
        - 12348:12345
    dataserver5: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver5:12345
      ports: 
        - 12349:12345
    dataserver6: 
      extends: 
        file: common-services.yml
        service: webapp
      environment:
        - LISTEN_ADDRESS=dataserver6:12345
      ports: 
        - 12350:12345
    apiserver: 
      build: 
          context: .
          dockerfile: ./Dockerfile.api
      environment:
        - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672
        - LISTEN_ADDRESS=apiserver:12445
        - ES_SERVER=elasticsearch:9200
      restart: always
      ports: 
        - 12445:12445
      depends_on:
        - rabbitmq
    apiserver2: 
      build: 
          context: .
          dockerfile: ./Dockerfile.api
      environment:
        - RABBITMQ_SERVER=amqp://guest:guest@rabbitmq:5672
        - LISTEN_ADDRESS=apiserver2:12445
        - ES_SERVER=elasticsearch:9200
      restart: always
      ports: 
        - 12446:12445
      depends_on:
        - rabbitmq
    rabbitmq:
        image: rabbitmq:management 
        restart: always
        ports: 
          - 5672:5672
          - 15672:15672
    elasticsearch:
        image: elasticsearch:7.12.0
        environment:
          - discovery.type=single-node
        ports:
          - 9200:9200
          - 9300:9300
 